### ISSUE TITLE
Readme missing information or extra steps required

### ISSUE THREAD

**Issue by Assambra** [youngmonkeys/ezyfox-server-csharp-client#26]
There is no hint that the unity package Newtonsoft Json is required or some installation steps for it.

Adding the Newton Json package in Unity via the Package Manager 
Window -> Package Manager -> Plus Sign -> Add package from git URL ->  insert into the URL flield -> com.unity.nuget.newtonsoft-json.

Or edit the manifest.json file in the Packages folder of your Unity project and add "com.unity.nuget.newtonsoft-json": "3.2.1",

**Comment by tvd12** [comment]
@Assambra could you check?

**Comment by Assambra** [comment]
Either
Adding the Newton Json package in Unity via the Package Manager
Window -> Package Manager -> Plus Sign -> Add package from git URL -> insert into the URL flield -> com.unity.nuget.newtonsoft-json. (This step will automaticly add it to the manifest.json)

"or manually"

Edit the manifest.json file in the Packages folder of your Unity project and add "com.unity.nuget.newtonsoft-json": "3.2.1",

**Comment by tvd12** [comment]
Can I close this issue if you don't have any another question?

**Comment by Assambra** [comment]
yes you can close it and thank you.
